### ISSUE TITLE
Rule Normalizes without "normalize" Keyword

### ISSUE THREAD

**Issue by wrharding** [quadrantsec/sagan#59] opened 2023-03-02 17:37 UTC
Running version 2.1.0, compiled from main branch on 2022-08-05 w/ commit bedc365f98cc9526b4cec32ca07069c51d2e6820. Similar behavior was observed first on a host running Sagan v2.1.0 from an unknown source compiled on 2022-10-19.

Expected behavior:
No normalization attempts occur without the rule/signature including the [`normalize`](https://sagan.readthedocs.io/en/latest/rule-keywords.html#normalize) keyword.

Observed behavior:
Normalized data exists in the alert.json entry when an alert does not have the `normalize` keyword.

Take the following rule as an example (with `windows-auth.rules` enabled):

```
alert any $EXTERNAL_NET any -> $HOME_NET any (msg:"[WINDOWS-AUTH] User Removed from Domain Administrators group"; pcre: "/ 633: | 4729: | 637: | 4733: | 661: | 4757: /"; pcre: "/S-1-5-21-\d{5,15}\-\d{5,15}\-\d{5,15}-512 /"; program: *Security*; classtype: successful-admin; sid: 1111111; rev:1;)
```
Along with the following log:

```
127.0.0.1|user|notice|notice|wharding-lae|2023-02-14T18:00:05Z|2023-02-14T18:00:05Z|Security| 4733: A member was removed from a security-enabled local group. Subject: Security ID: S-1-5-21-3623811015-3361044348-30300820-1000 Account Name: wharding Account Domain: wharding-w2k22 Logon ID: 0x1479200E Member: Security ID: S-1-5-21-1085031214-1563985344-725345543-512 Account Name: - Group: Security ID: S-1-5-32-544 Group Name: Administrators Group Domain: Builtin Additional Information: Privileges: -
```
Finally, the output:

```
{ "timestamp": "2023-03-02T17:11:54.940490+0000", "flow_id": 3638188490, "in_iface": "logs", "event_type": "alert", "src_ip": "192.168.2.1", "src_port": 514, "dest_ip": "192.168.2.1", "dest_port": 514, "proto": "UDP", "payload": "IDQ3MzM6IEEgbWVtYmVyIHdhcyByZW1vdmVkIGZyb20gYSBzZWN1cml0eS1lbmFibGVkIGxvY2FsIGdyb3VwLiBTdWJqZWN0OiBTZWN1cml0eSBJRDogUy0xLTUtMjEtMzYyMzgxMTAxNS0zMzYxMDQ0MzQ4LTMwMzAwODIwLTEwMDAgQWNjb3VudCBOYW1lOiB3aGFyZGluZyBBY2NvdW50IERvbWFpbjogd2hhcmRpbmctdzJrMjIgTG9nb24gSUQ6IDB4MTQ3OTIwMEUgTWVtYmVyOiBTZWN1cml0eSBJRDogUy0xLTUtMjEtMTA4NTAzMTIxNC0xNTYzOTg1MzQ0LTcyNTM0NTU0My01MTIgQWNjb3VudCBOYW1lOiAtIEdyb3VwOiBTZWN1cml0eSBJRDogUy0xLTUtMzItNTQ0IEdyb3VwIE5hbWU6IEFkbWluaXN0cmF0b3JzIEdyb3VwIERvbWFpbjogQnVpbHRpbiBBZGRpdGlvbmFsIEluZm9ybWF0aW9uOiBQcml2aWxlZ2VzOiAt", "stream": "0", "xff": "192.168.2.1", "facility": "user", "priority": "notice", "level": "notice", "program": "Security", "host": "default_sensor_name", "alert": { "action": "allowed", "gid": 1, "signature_id": 8070004, "rev": 1, "signature": "[WINDOWS-AUTH] User Removed from Domain Administrators group", "category": "Successful Administrator Privilege Gain", "severity": 1, "rule": "alert any $EXTERNAL_NET any -> $HOME_NET any (msg:\"[WINDOWS-AUTH] User Removed from Domain Administrators group\"; pcre: \"\/ 633: | 4729: | 637: | 4733: | 661: | 4757: \/\"; pcre: \"\/S-1-5-21-\\d{5,15}\\-\\d{5,15}\\-\\d{5,15}-512 \/\"; program: *Security*; classtype: successful-admin; sid: 8070004; rev:1;)" }, "normalize": {"originalmsg":" 4733: A member was removed from a security-enabled local group. Subject: Security ID: S-1-5-21-3623811015-3361044348-30300820-1000 Account Name: wharding Account Domain: wharding-w2k22 Logon ID: 0x1479200E Member: Security ID: S-1-5-21-1085031214-1563985344-725345543-512 Account Name: - Group: Security ID: S-1-5-32-544 Group Name: Administrators Group Domain: Builtin Additional Information: Privileges: -","unparsed-data":"Group: Security ID: S-1-5-32-544 Group Name: Administrators Group Domain: Builtin Additional Information: Privileges: -"} }
```

Consider the output WITHOUT `windows-auth.rules` enabled:

Same rule as above.

Same log as above.

New output:
```
{ "timestamp": "2023-03-02T17:32:19.381383+0000", "flow_id": 3718500807, "in_iface": "logs", "event_type": "alert", "src_ip": "192.168.2.1", "src_port": 514, "dest_ip": "192.168.2.1", "dest_port": 514, "proto": "UDP", "payload": "IDQ3MzM6IEEgbWVtYmVyIHdhcyByZW1vdmVkIGZyb20gYSBzZWN1cml0eS1lbmFibGVkIGxvY2FsIGdyb3VwLiBTdWJqZWN0OiBTZWN1cml0eSBJRDogUy0xLTUtMjEtMzYyMzgxMTAxNS0zMzYxMDQ0MzQ4LTMwMzAwODIwLTEwMDAgQWNjb3VudCBOYW1lOiB3aGFyZGluZyBBY2NvdW50IERvbWFpbjogd2hhcmRpbmctdzJrMjIgTG9nb24gSUQ6IDB4MTQ3OTIwMEUgTWVtYmVyOiBTZWN1cml0eSBJRDogUy0xLTUtMjEtMTA4NTAzMTIxNC0xNTYzOTg1MzQ0LTcyNTM0NTU0My01MTIgQWNjb3VudCBOYW1lOiAtIEdyb3VwOiBTZWN1cml0eSBJRDogUy0xLTUtMzItNTQ0IEdyb3VwIE5hbWU6IEFkbWluaXN0cmF0b3JzIEdyb3VwIERvbWFpbjogQnVpbHRpbiBBZGRpdGlvbmFsIEluZm9ybWF0aW9uOiBQcml2aWxlZ2VzOiAt", "stream": "0", "xff": "192.168.2.1", "facility": "user", "priority": "notice", "level": "notice", "program": "Security", "host": "default_sensor_name", "alert": { "action": "allowed", "gid": 1, "signature_id": 8070004, "rev": 1, "signature": "[WINDOWS-AUTH] User Removed from Domain Administrators group", "category": "Successful Administrator Privilege Gain", "severity": 1, "rule": "alert any $EXTERNAL_NET any -> $HOME_NET any (msg:\"[WINDOWS-AUTH] User Removed from Domain Administrators group\"; pcre: \"\/ 633: | 4729: | 637: | 4733: | 661: | 4757: \/\"; pcre: \"\/S-1-5-21-\\d{5,15}\\-\\d{5,15}\\-\\d{5,15}-512 \/\"; program: *Security*; classtype: successful-admin; sid: 8070004; rev:1;)" }, "normalize": null }
```

Is Sagan normalizing a log the first time it encounters a rule that includes the `normalize` keyword and then applying that to all future rules? Does Sagan re-run normalization each time it encounters a rule that includes `normalize`? Is including the normalized data in the alert.json entry when a rule/sig does not include the `normalize` keyword intentional?

**Comment by quadrantsec** [comment] 2023-03-02 19:44
Normalization only happens once.  Since the same log line is being analyzed by multiple signatures,  re-normalizing it is a waste of CPU and the results will always be the same. 

You are correct,  if Sagan runs into a "normalize" keyword,  it will retain that data and store it in the JSON even if the signature does not have "normalize" in it.   

I believe the thinking was, "Well, I've already spent the CPU normalizing the data,  I might as well use it".   Let me know if you see issues in my thought process. 

Also,  can you update to the latest git code?  I want to make sure Sagan acts as expected with normalized data.

**Comment by wrharding** [comment] 2023-03-02 20:04
Sounds great to me! The code is too dense for me to follow or else I would have verified without creating an issue. I will make a PR to add this to the documentation as I did not see it when reviewing. I'll try it with the code at aaf638454d033ba35c55151ec33813072bdba949 ASAP!

**Comment by CyberTaoFlow** [comment] 2023-03-08 23:24
seems possibly related to https://github.com/beave/sagan/issues/119
There it is noted:
```
 In order for normalization to really happen, at least one rule has to have the "normalize;" option in it. If normalization isn't on, the liblognorm json value will be "null". I dont see this being a big deal.

**Comment by quadrantsec** [comment] 2023-03-17 20:01
Thanks. I'm going to close this as it is expected behavior.

**Closed by quadrantsec** 2023-03-17 20:01 UTC
